### ISSUE TITLE
How to build this project?

### ISSUE THREAD

**Issue by 6769** [44670/p7zip-wasm#2]
This project's idea is a nice try on Browser/Chrome OS,
while without build process script(build.sh, Makefile, etc...), it's hard to reproduce the target that code aimed at.

like this REPO: https://github.com/use-strict/7z-wasm
Could you please add the build steps when you are free?

**Comment by 44670** [comment]
Currently we are still experimenting with various compilation parameters/wasm features and the build script is not ready to be uploaded yet. It is recommended to try to compile it based on existing CMake files.
