### ISSUE TITLE
能支持密码解压吗?

### ISSUE THREAD

**Issue by nenge123** [44670/p7zip-wasm#3]
RT

**Comment by 44670** [comment]
技术上没有问题，需要花些时间，p7z的代码写得比较难懂。

**Comment by nenge123** [comment]
之前用单文件7z.js的（280KB），压缩成zip加载不到100KB,但是只能解压7z，

我觉得这个还有压缩到更小的可能吧？例如把里面的压缩去掉，纯解压。

**Comment by 44670** [comment]
这个支持rar/zip/一堆其它的没有测试过的格式。

项目的目标是有一个和windows上7z类似的GUI，可供交互式浏览、选取，会比命令行方式的要复杂。

**Comment by nenge123** [comment]
Gui可以参考retroarch

不过其实完全可以html实现，只要你接口够

如果你要用gui那就是不用worker，


postmessage看起来炫酷，实际上不用也会有多大性能区别，都是异步操作。至于担心全局污染大可以在wasm js前后加上

cosnt My={Module:{}};
((Module)=>{....})(My.Module)

**Comment by 44670** [comment]
worker是因为需要支持大文件的流式处理（而非全部读入到内存中），并且还要支持进度条之类的。

**Comment by nenge123** [comment]
web worker可以读2GB?

不过超过1GB已经是node那种使用，一般浏览器处理300MB以下，我自己试过苹果11超过300M读取到内存概率崩溃

如果搞界面，最好面向百毒云这种解压都收费的，这样手机用户不受压缩文件之苦。搞大一一点集成在线office文件在线查看

**Comment by 44670** [comment]
这个支持10GB以上的压缩文件。

文件预览也在计划内，不过可能不会做太复杂的功能。

**Comment by nenge123** [comment]
牛逼！
